[package]
name = "lucasdb"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.64"
parking_lot = "0.12.3"
env_logger = "0.11.5"
log = "0.4.22"
bytes = "1.7.2"

[dev-dependencies]
anyhow = "1.0.89"
