[package]
name = "http"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
lucasdb = { path = "../../lucasdb" }
quote = "1.0.37"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
